In [1]:
import numpy as np
import pandas as pd

# Test 1

In [3]:
%cat test1.txt

4
2 -5 3 1
3 -7 3 -1
5 -9 6 2
4 -6 3 1
5 -1 7 8


In [4]:
X = np.array([[2, -5, 3, 1],
              [3, -7, 3, -1],
              [5, -9, 6, 2],
              [4, -6, 3, 1]])
y = np.array([5, -1, 7, 8])
for x in np.linalg.solve(X, y):
    print("%lf" % x, end=' ')

0.000000 -3.000000 -5.333333 6.000000 

In [9]:
np.dot(X, X.T)

array([[ 39,  49,  75,  48],
       [ 49,  68,  94,  62],
       [ 75,  94, 146,  94],
       [ 48,  62,  94,  62]])

In [11]:
for x in np.linalg.solve(np.dot(X, X.T), y):
    print("%lf" % x, end=' ')

14.333333 -3.888889 -10.629630 9.037037 

In [36]:
print(np.linalg.inv(X))

[[-1.00000000e+00  3.05311332e-17  3.33333333e-01  3.33333333e-01]
 [-1.00000000e+00  9.71445147e-17  6.66666667e-01 -3.33333333e-01]
 [-1.00000000e+00  1.66666667e-01  1.05555556e+00 -9.44444444e-01]
 [ 1.00000000e+00 -5.00000000e-01 -5.00000000e-01  5.00000000e-01]]


In [37]:
np.linalg.det(X)

17.999999999999996

# Test 2

In [9]:
%cat test2.txt

4
4 3 -9 1
2 5 -8 -1
2 16 -14 2
2 3 -5 -11
9 8 24 7


In [10]:
X = np.array([[4, 3, -9, 1],
              [2, 5, -8, -1],
              [2, 16, -14, 2],
              [2, 3, -5, -11]])
y = np.array([9, 8, 24, 7])
for x in np.linalg.solve(X, y):
    print("%lf" % x, end=' ')

3.000000 2.000000 1.000000 -0.000000 

In [44]:
print(np.linalg.inv(X))

[[ 0.68894009 -1.3640553   0.25345622  0.23271889]
 [ 0.11751152 -0.50691244  0.18202765  0.08986175]
 [ 0.23963134 -0.77880184  0.17511521  0.12442396]
 [ 0.0483871  -0.03225806  0.01612903 -0.08064516]]


In [45]:
np.linalg.det(X)

-867.9999999999995

# Test 3

In [2]:
%cat test3.txt

4
12 14 -15 24
16 18 -22 29
18 20 -21 32
10 12 -16 20
5 8 9 4


In [12]:
X = np.array([[12, 14, -15, 24],
              [16, 18, -22, 29],
              [18, 20, -21, 32],
              [10, 12, -16, 20]])
y = np.array([5, 8, 9, 4])
for x in np.linalg.solve(X, y):
    print("%lf" % x, end=' ')

2.222222 -1.666667 -0.111111 0.000000 

In [48]:
print(np.linalg.inv(X))

[[ 1.00000000e+00  2.88888889e+00 -1.66666667e+00 -2.72222222e+00]
 [-2.50000000e+00 -4.66666667e+00  3.50000000e+00  4.16666667e+00]
 [-5.42775701e-16 -4.44444444e-01  3.33333333e-01  1.11111111e-01]
 [ 1.00000000e+00  1.00000000e+00 -1.00000000e+00 -1.00000000e+00]]


In [49]:
np.linalg.det(X)

35.99999999999984

# Test 4

In [13]:
%cat test4.txt

4
2 1 4 8
1 3 -6 2
3 -2 2 -2
2 -1 2 0
-1 3 8 4


In [14]:
X = np.array([[2, 1, 4, 8],
              [1, 3, -6, 2],
              [3, -2, 2, -2],
              [2, -1, 2, 0]])
y = np.array([-1, 3, 8, 4])
print(np.linalg.solve(X, y))

[ 2.  -3.  -1.5  0.5]


# Test 5

In [15]:
%cat test5.txt

4
18 57 55 23
57 198 188 94
55 188 182 87
23 94 87 55
242 829 795 385



In [16]:
X = np.array([[18, 57, 55, 23],
              [57, 198, 188, 94],
              [55, 188, 182, 87],
              [23, 94, 87, 55]])
y = np.array([242, 829, 795, 385])
for x in np.linalg.solve(X, y):
    print("%lf" % x, end=' ')

1.000000 2.000000 2.000000 0.000000 

# Test 6

In [17]:
%cat test6.txt

3
2 -1 0
-1 2 -1
0 -1 2
1 1 1


In [18]:
X = np.array([[2, -1, 0],
              [-1, 2, -1],
              [0, -1, 2]])
y = np.array([1, 1, 1])
for x in np.linalg.solve(X, y):
    print("%lf" % x, end=' ')

1.500000 2.000000 1.500000 

In [4]:
n = 20.0
m = 8.0
A = []
y = []
for i in range(20):
    A.append([])
    for j in range(20):
        if (i == j):
            A[i].append(n + m ** 2 + float(j) /m + float(i)/n)
        else:
            A[i].append((float(i) + float(j))/(n + m))
    y.append(200.0 + 5.0 * i)

X = np.linalg.solve(A, y)
X

array([2.16903211, 2.20456485, 2.24001019, 2.27536843, 2.31063992,
       2.34582495, 2.38092386, 2.41593696, 2.45086455, 2.48570697,
       2.5204645 , 2.55513747, 2.58972619, 2.62423096, 2.65865208,
       2.69298986, 2.7272446 , 2.76141661, 2.79550617, 2.8295136 ])

In [5]:
for i in X:
    print(i)

2.1690321121291753
2.204564853240064
2.2400101866410336
2.2753684344598772
2.310639917243458
2.345824953967395
2.3809238620456856
2.41593695734024
2.450864554170366
2.4857069653221733
2.5204645020579024
2.5551374741251998
2.5897261897663273
2.6242309557272767
2.6586520772668543
2.6929898581656793
2.727244600735109
2.7614166058261325
2.795506172838155
2.8295135997277634


In [21]:
np.linalg.det(A)

4.46407682313798e+38

In [22]:
np.linalg.inv(A)

array([[ 1.19092762e-02, -2.09387469e-07, -4.92140339e-06,
        -9.62184236e-06, -1.43107470e-05, -1.89881597e-05,
        -2.36541227e-05, -2.83086779e-05, -3.29518672e-05,
        -3.75837321e-05, -4.22043141e-05, -4.68136541e-05,
        -5.14117934e-05, -5.59987726e-05, -6.05746323e-05,
        -6.51394129e-05, -6.96931546e-05, -7.42358973e-05,
        -7.87676810e-05, -8.32885451e-05],
       [-2.09387469e-07,  1.18852168e-02, -9.54852146e-06,
        -1.42008795e-05, -1.88418211e-05, -2.34713884e-05,
        -2.80896231e-05, -3.26965668e-05, -3.72922607e-05,
        -4.18767461e-05, -4.64500639e-05, -5.10122549e-05,
        -5.55633596e-05, -6.01034184e-05, -6.46324715e-05,
        -6.91505588e-05, -7.36577201e-05, -7.81539950e-05,
        -8.26394229e-05, -8.71140429e-05],
       [-4.92140339e-06, -9.54852146e-06,  1.18613129e-02,
        -1.87686525e-05, -2.33617492e-05, -2.79435888e-05,
        -3.25142126e-05, -3.70736617e-05, -4.16219771e-05,
        -4.61591996e-05, -5.0

In [17]:
np.allclose(np.dot(A, X), y)

True

In [18]:
X2 = [1.691244, 2.226726, 2.760892, 3.293744, 3.825289, 4.355532, 4.884476, 5.412127, 5.938490, 6.463569, 6.987369,
        7.509895, 8.031150, 8.551141, 9.069871, 9.587345, 10.103568, 10.618544, 11.132278, 11.644773]

In [19]:
np.allclose(np.dot(A, X2), y)

False